### ISSUE TITLE
Audit DOs for atomacity issues

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#115]
@divergentdave pointed out in https://github.com/cloudflare/daphne/pull/112 at least one instance in which DO storage transaction atomicity was broken by an `await`. Now that we understand this better, we need to come through the code to see if there are any other issues like this.

Note that #73 is relevant here as well.

**Comment by bhalleycf** [comment]
I think I have fixed #73 and didn't find any similar issues after an audit of the other DOs.

**Comment by cjpatton** [comment]
Great, thanks! I guess we can close this then.
