### ISSUE TITLE
Upgrade to hpke 0.10.0

### ISSUE THREAD

**Issue by divergentdave** [cloudflare/daphne#147]
We just landed a change in Janus to upgrade to hpke 0.10.0, which removed a too-restrictive dependency bound on `zeroize` from a transitive dependency. I'm filing this issue to let you know that you'll need to update this as well when bumping your Janus git dependency. (in fact, it's possible bumping Janus may unblock #119, if that's failing to resolve dependencies for the same reason)

**Comment by cjpatton** [comment]
Thanks!
