### ISSUE TITLE
Changes for DAP-03

### ISSUE THREAD

**Issue by bhalleycf** [cloudflare/daphne#165]
This is a preliminary list:

- [x] FixedSizeQuery changes
- [x] Query and BatchSelector are now different
- [x] In collect requests, a Query with a FixedSize CurrentBatch must be converted into a FixedSize ByBatchId by selecting a batch.
- [x] Change input share encryption and decryption functions to use dap-03
- [x] Verify compliance with all updated error conditions
- [x] agg_param in AggregateInitializeReq, AggregateShareReq, and CollectReq now have a 32-bit length prefix instead of a 16-bit prefix
- [x] Change aggregate share encryption and decryption functions to use dap-03.
- [x] Examine policy around validation of batch IDs for fixed size tasks and update if necessary
- [x] Add support for PlaintextInputShare; extensions now live there.   (this is in the second batch of DAP-03 changes)

**Comment by bhalleycf** [comment]
The first batch of DAP-03 changes has been merged, but this issue will remain open to track further DAP-03 work.

**Comment by cjpatton** [comment]
Additional things:

- [ ] Move extensions to encrypted input shares and make them mandatory to implement: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/373
- [ ] Enforce non-repeating extensions: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/379
- [ ] Enforce anti-replay based on timestamp+nonce and revisit whether to shard ReportsProcessed should be sharded by "epic". (See TODOs in that section.)
