### ISSUE TITLE
Daphne: Expose a "mock" backend in a public module

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#20]
`MockAggregator` in `daphne/src/roles_test.rs`, once finished, will be a useful tool for demonstrating the functionality the Daphne backend is supposed to provide. This should be put in a public module for others to copy-paste or refer to as needed.

While at, let's write tests that excercise the protocol logic with the mock backend.

**Comment by cjpatton** [comment]
cc/ @nakatsuka-y

**Comment by nakatsuka-y** [comment]
# Immediate tasks
- [ ] Implement HpkeDecrypter methods (Ref: #32)
- [ ] Implement DapAggregator methods
- [ ] Implement DapHelper methods
- [ ] Implement DapLeader methods

# Next steps
- [ ] Use MockAggregator to simulate Leader - Helper interactions
- [ ] Use MockAggregator to simulate Leader - Collector interactions
- [ ] Expose MockAggregator to public

**Comment by nakatsuka-y** [comment]
We should have implemented all the necessary components.
I will be closing this issue, but feel free to re-open and ping me if there are any missing things related to this issue.
