### ISSUE TITLE
Add rustfmt to CI

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#200]
_Originally posted by @cjpatton in https://github.com/cloudflare/daphne/pull/198#discussion_r1073845446_

**Comment by bhalleycf** [comment]
Just a note that my advice to set things in rustfmt's config is not in fact helpful, as the things we want to change, namely

comment_width = 100
wrap_comments = true

Are both unstable features and can only be used with an unstable tool change.  The stable code does not wrap comments.  So for now we have to do this in the IDE.  Also the default for comment_width is 80 FWIW.

**Comment by bhalleycf** [comment]
Closing as support was added.
