### ISSUE TITLE
E2E races

### ISSUE THREAD

**Issue by bhalleycf** [cloudflare/daphne#241]
Various E2E tests will occasionally fail because the amount of time they wait for processing to be complete happens not to be enough, and thus count checks fail as some data is not yet processed.

It would be good to have a "wait until the value is X" type of test which polled (or was event driven, though not sure how to do that in this case!), with a sufficiently long timeout instead of just waiting a fixed amount of time.  Alternatively in the short run we can extend the wait time, although this is still prone to failure and is not optimal for test runtime.

**Comment by cjpatton** [comment]
I haven't seen this happen in quite a while. @bhalleycf do you think we may have fixed this by now?

**Comment by cjpatton** [comment]
We haven't triggered these in a while, so I'm going to assume this isn't an issue anymore.
