### ISSUE TITLE
docker: Use wrangler instead of miniflare

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#252]
miniflare.Dockerfile uses miniflare@2.11.0:
https://github.com/cloudflare/daphne/blob/main/docker/miniflare.Dockerfile#L23

We should switch to wrangler@latest, since this is what we actually use in tests.

**Comment by bhalleycf** [comment]
I have this working on the docker branch now, though I haven't gotten "experimental-local" working yet.  It uses pre-compiled stuff so does not cause a rust build at deployment time.

**Comment by cjpatton** [comment]
I suspect we should be good to go as of wrangler 3.

**Comment by bhalleycf** [comment]
agreed!
