### ISSUE TITLE
daphne_worker: Add hostname as label to metrics

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#263]
I.e., instead of

```rust
﻿﻿﻿﻿self.metrics()
    .report_counter
    .with_label_values(&[&format!("rejected_{failure}")])
    .inc();
```                        

write

```rust
﻿﻿﻿﻿self.metrics()
    .report_counter
    .with_label_values(&[self.host(),  &format!("rejected_{failure}")])
    .inc();
```

where `host(&self) -> &str` is a callback that returns the hostname of the server.

This will require exposing the hostname for a request in the workers-rs. Right now only the path is parsed: https://github.com/cloudflare/workers-rs/blob/main/worker/src/request.rs#L31-L39

**Comment by dorryspears** [comment]
@cjpatton can I tackle this as a first issue?

**Comment by cjpatton** [comment]
Hi @dorryspears, sure!

**Comment by cjpatton** [comment]
Ahhh, the `Url` is available via the `DapRequest`, so we don't need to make any changes to workers-rs.

**Comment by dorryspears** [comment]
#264 made PR

**Comment by cjpatton** [comment]
Work in progress. One more requirement to note here: Workers can listen on multiple routes, each with a different hostname. Thus we need to use the hostname indicated in the HTTP request. In particular, we can't use the URLs defined in the task config, as these may differ.
