### ISSUE TITLE
Interop test API compliance

### ISSUE THREAD

**Issue by divergentdave** [cloudflare/daphne#268]
I tested the container image `cloudflare/daphne-worker-helper:sha-b150547` and ran into three issues, all with the test API and not DAP.

- The process in the container listens on port 8787 instead of 8080.
  - Nice-to-have: an `EXPOSE` directive in the Dockerfile would simplify manual use, as it would let you use `--publish-all`.
- It expects requests to `/internal/test/add_task` to have a `verify_key` attribute instead of `vdaf_verify_key`. (this changed in a subsequent draft version)
- It expects VDAF types to be "Prio3Aes128Count" and "Prio3Aes128Sum" instead of "Prio3Count" and "Prio3Sum".

**Comment by bhalleycf** [comment]
Fixed by #273 and docker improvements in #278.
