### ISSUE TITLE
Handle missing media type in draft04 collection job polling.

### ISSUE THREAD

**Issue by bhalleycf** [cloudflare/daphne#275]
The #270 fix did not cover this after all, as I found out in some re-testing.  (I had left one of my fixes related to this issue in the code the first time, so I didn't notice that 270 wasn't sufficient.)

When doing collection job polling, draft04 does not have a media type, and we thus need to extract the collection job id directly rather than by using our resource field.

**Comment by cjpatton** [comment]
Did you notice this because one of our tests, or perhaps one of @divergentdave's? As of #270 we are strictly enforcing the media type for many requests, it's possible we missed this one.

**Comment by bhalleycf** [comment]
Yes, as I was assembling the PRs I was testing the updated code on divergentdave's tests to make sure I didn't break anything, and it broke with just 270.  I looked at what I had before and noticed that it had the one change in this PR in addition to 270.

**Comment by bhalleycf** [comment]
Fixed by #275.
