### ISSUE TITLE
Running tests via docker-compose takes a long time

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#31]
The culprit is `cargo install worker-build`, which is run on line `RUN wrangler build` in `miniflare.Dockerfile`. We should build/install `worker-build` prior to copying the source files so that we don't need to re-run this layer each time the files change.

**Comment by cjpatton** [comment]
In any case it seems like it's due to a fairly recent change to the dependencies of `workers-rs`.

**Comment by divergentdave** [comment]
If you're willing to commit to using Docker Buildkit (which requires either passing an environment variable or setting some global configuration), you can make use of cache mounts to reuse both the cargo registry and your project's target directory between builds. See https://github.com/divviup/janus/blob/2d884e6e239535f8f9894da6c639577f90201605/Dockerfile#L13 for how we have done this.

However, it appears that wrangler kicks off another Cargo build when you run the container, so moving the target directory out of the container image and onto a build time-only cache mount wouldn't work. I'm not too familiar with with wrangler, but would it be possible to do all the WASM compilation steps during container building, and change the entrypoint to call miniflare directly with the `/tmp/dap_test/daphne_worker_test/build` directory? I think that may let you keep the target directory out of the container image.
