### ISSUE TITLE
daphne_worker: Garbage collect `AggregateStore` instances we don't need anymore

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#345]
Similar to `ReportsProcessed`, instances of `AggregateStore` can be garbage collected by setting an alarm to delete the instance when it is first touched.

Some requirements:
* The lifetime should be configurable via an environment variable
* We need to make sure to delete instances only after there not likely to be collected (this depends on SLAs)

**Comment by mendess** [comment]
Fixed by #554
