### ISSUE TITLE
DAP-07

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#350]
The plan will be to push changes to a development branch ([draft05](https://github.com/cloudflare/daphne/tree/draft05)) until we're ready to drop support for DAP-04.

- [ ] Bump version
- [x] Ping-pong flow
- [ ] PUT idempotency https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/471/files
- [ ] Implement the latest taskprov version

**Comment by cjpatton** [comment]
Can we rename ﻿﻿`Transition` to `PrepareResp`?

**Comment by mendess** [comment]
`PrepareState`? Since it's basically a state machine?
