### ISSUE TITLE
`janus_helper` test not working

### ISSUE THREAD

**Issue by nakatsuka-y** [cloudflare/daphne#36]
`janus_helper`, one of the 2 `janus` tests implemented in the `daphne_worker_test` set, fails during my testing with the following error message: `thread 'main' panicked at 'failed to start container'`.

**Comment by cjpatton** [comment]
Is your Docker daemon up? On macOS you can use "Docker Desktop"

**Comment by nakatsuka-y** [comment]
Yes, you are absolutely right!
Let me send a PR that adds this instruction in the `daphne_worker_test` README.
