### ISSUE TITLE
Handle collect requests properly

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#45]
Daphne is currently missing https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/277, which is needed for privacy. However the exact requirements for collect requests (and constraints on them) are a bit of a moving target. (See https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/195.)

**Comment by cjpatton** [comment]
(This isn't really a bug per se, it's more of a feature parity issue.)

**Comment by cjpatton** [comment]
One thought I had here while reviewing #63: The Leader should reject collect requests for which:
* The batch interval is *huge*, in the sense that it spans more than, say, 100 time windows. Otherwise updating ReportStore buckets after a batch is aggregated will be expensive.
* The start of the batch interval is too far in the past, say more than a few days. Otherwise we might end up holding onto a request for which we're not likely to get any data.
* The end of the batch interval is too far in the future, say more than a few hours. Similar reasoning as above.

**Comment by cjpatton** [comment]
Suggestion for how to proceed:
* Mark each AggreagteStore DO instance as collected or not collected.
* When a collect request comes in, for each batch window, check the AggreagteStore to see if it has been collected. If so, reject. Otherwise, if none have been collected, accept.

**Comment by nakatsuka-y** [comment]
Closing as #63 has been merged to main branch.

**Comment by cjpatton** [comment]
Ropened due to bug spotted after merging the main PR. This condition is wrong:
https://github.com/cloudflare/daphne/blob/main/daphne_worker/src/dap.rs#L358-L359

There is a similar issue on the Helper side.
