### ISSUE TITLE
Daphne-Worker: Large report or agg shares and durable objects

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#47]
Values stored in durable objects can be no more than 128KB in size: https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#:~:text=values%20are,131072%20bytes

We may end up having to store reports that are larger than this. This is more of a problem for reports: For Prio3, for example, the report also encodes the proof, which is typically linear in the length of the input (often 2 times the size).

**Comment by cjpatton** [comment]
Answer might be to store reports in KV.

**Comment by cjpatton** [comment]
@mendess is this issue closed by https://github.com/cloudflare/daphne/pull/407?

**Comment by mendess** [comment]
@cjpatton yes
