### ISSUE TITLE
Handle requests to "Collect URIs" properly

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#53]
When a GET request to a Collect URI is successful, Daphne-Worker deletes the associated state. I believe this is incorrect, since subsequent GET requests are supposed to return the same results, per HTTP semantics.

Further, collect URIs are issued only to authorized senders (i.e., the Collector that presents the right API token), however polling the URI does not require authorization, per the spec. This means an unauthenticated endpoint can change the Leader's state, which is problematic.

The short term solution is to change Daphne-Worker so that it handles these GET requests properly by storeing collect responses indefinitely. In the long term, we might consider changing the protocol so that the Leader is free to drop this state after a period of time.

**Comment by chris-wood** [comment]
There's no requirement for the server to keep the resource available after a GET. It could choose to remove or modify it as it sees fit. It would probably make sense to let the collector [DELETE](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#DELETE) the collect result opportunistically. But the worker should also feel free to delete this state as needed.

**Comment by cjpatton** [comment]
Cool. In that case, do you think it would be worth changing to DAP to require authentication for accessing this? There's no requirement that the URI is hard to guess, so it seems seems like we should only delete it after the real collector gets access.

**Comment by cjpatton** [comment]
I'll file an issue for DAP. In the meantime, I suppose the fix here ought to be to make our collect URIs hard to guess. Currently they are not, but we can make them so by replacing the ["collect_id"](https://github.com/cloudflare/daphne/blob/main/daphne_worker/src/durable/leader_state_store.rs#L71-L73), currently the hash of the collect request, with a randomly generated one.

**Comment by mnot-cloudflare** [comment]
I'm more concerned that the GET appears to be having side effects (the deletion of the resource). If you view the GET as triggering the deletion, that's counter to its [safety](https://httpwg.org/specs/rfc9110.html#rfc.section.9.2.1):

> the client does not request, and does not expect, any state change on the origin server as a result of applying a safe method to a target resource.

[...]

> The purpose of distinguishing between safe and unsafe methods is to allow automated retrieval processes (spiders) and cache performance optimization (pre-fetching) to work without fear of causing harm. In addition, it allows a user agent to apply appropriate constraints on the automated use of unsafe methods when processing potentially untrusted content.

OTOH if you view this as garbage collection -- i.e., the server is removing resources that it's very very confident are not useful any more -- that's fine; like Chris says, the server manages its own resources. Just be aware that GETs could be caused by a variety of bits of software (virus scanners, spiders, whatever) so if it's not authenticated, it's a bit risky.

**Comment by cjpatton** [comment]
Yeah, this situation is arguably "garbage collection". However It was pointed out in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/288 that the DAP spec actually calls for this state to be cleared explicitly by the Collector via an HTTP DELETE. However, it's a bit ambiguous as to whether the server is allowed to "garbage collect" immediately or has to keep it around for some period of time.

Anywho, https://github.com/cloudflare/daphne/pull/55 makes the URI unpredictable, which is a step in the right direction.

**Comment by cjpatton** [comment]
Closing this as "complete". Any changes will need to be specified in the next DAP draft.
