### ISSUE TITLE
Support flexible report grouping

### ISSUE THREAD

**Issue by nakatsuka-y** [cloudflare/daphne#65]
DAP currently groups reports based on the time when they are generated.

There are several proposals for making this more flexible:
1. [#273](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/273): Grouping reports into "fixed-sized chunks"
2. [#183](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/183): Grouping reports by "client properties"

Additionally, PR [#297](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/297) proposes a change in the DAP spec to support the "fixed-sized chunk" case.

Following the proposals, Daphne should add the following changes:

- [ ]  The generalized concept of a `query`
- [ ] Methods that filter reports based on the query

Daphne must also prevent intersection attacks launched by malicious Collectors over this flexible grouping:
- [ ] Implement intersection attack prevention mechanisms for all query types

Note that this prevention will abide by the [DAP-01 spec](https://www.ietf.org/id/draft-ietf-ppm-dap-01.html#section-4.4.5-6.1), meaning that no report or aggregate share shall be collected twice.
However, as stated in [#183](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/183), this renders the "client property" grouping and many other use cases (e.g., drilling) useless.
This will be targeted for future implementation.

**Comment by nakatsuka-y** [comment]
Here are plans for supporting "fixed-sized chunks" in Daphne:
1. Add `QueryType`, `ChunkQueryType`, `ChunkQuery`, and `Query` in `messages.rs`
2. Add `QueryConfig` in `lib.rs` and add `QueryConfig` element to `TaskConfig`
3. Replace all `BatchInterval`s in Daphne with `Query` to reflect the changes (including messages that use `batch_interval`)
4. Reflect changes to how different entities in Daphne stores data. Especially Report store and Agg share store store state associating them with batch windows. The implementation would be different from MockAggregator and Daphne Workers.
5. Implement methods that check the query received by the Collector (batch boundaries, number of reports requested, and batch overlap)
6. Implement test cases where the Collector sends different types of queries.

**Comment by cjpatton** [comment]
This will be addressed in #100
