### ISSUE TITLE
Versioning the endpoints

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#71]
We're anticipating the need to support multiple DAP versions simultaneously. In particular, https://github.com/cloudflare/daphne/issues/65 will introduce changes that are incompatible with DAP-01. Thus, we'll need to gate these changes for DAP-02.

As discussed on the mailing list [1], we could version our leader and helper URL endpoints so that the client (or collector) opts-in to a particular version by picking a particular endpoint. For example, to upload a report for DAP-02, the client POST to `/02/upload` instead of `/upload`.

Some additional requirements:
* We would need to plumb the draft version through `DapRequest`. We could add a field whose value is
```rust
enum DapVersion {
    Draft01,
    Draft02,
}
```
* We probably should lock each task to a particular version. (Not sure if this requires a spec change.) To do so we could add the `DapVersion` to the `DapTaskConfig` structure.

@nakatsuka-y what do you think of this as a first step towards solving #65?
  

[1] https://mailarchive.ietf.org/arch/msg/ppm/svv73HxLvTMdOqk2fLyuWmZRU6Q/

**Comment by nakatsuka-y** [comment]
I think this is definitely required to clearly distinguish different versions.
I would suggest changing `/02/upload` to `/v2/upload` to make it more explicit that we are referring to `version`.

**Comment by cjpatton** [comment]
Hmm, yeah that's a good idea. I thought of "02" because it's reminiscent of the draft. How about `v02`?
