### ISSUE TITLE
Properly opt out of taskprov tasks

### ISSUE THREAD

**Issue by mendess** [cloudflare/daphne#710]
Discussion: https://github.com/cloudflare/daphne/pull/709#discussion_r1823230576

Relevant spec: https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap-taskprov/draft-ietf-ppm-dap-taskprov.html#section-4.4-3.1.1

We don't reject when a task id does not match the task config

**Comment by cjpatton** [comment]
To clarify: This only happens when we've already configured the task, in which case we use the previously configured task config to handle the request and not the advertised config.
