### ISSUE TITLE
Clean up: Awkward tension between task config version and leader endpoint

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#81]
We want that the serialized `DapTaskConfig` matches more or less what is shared between the Aggregators. In particular, our endpoint URL should include the DAP draft in the path. However, the leader also needs the version itself in the task config so that it can produce a `DapRequest` with a version properly.

One way to resolve this might be to make the Version field in the DapRequest optional.

**Comment by bhalleycf** [comment]
This was done as part of #171.
